version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
      - "1000:1000"
  escrowme:
    build:
      context: .
      args:
        - NODE_ENV:development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run dev
  socket:
    build:
      context: .
      args:
        - NODE_ENV:development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run dev1
