version: '3'
services:
  nginx:
   image: nginx:stable-alpine
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/live/escrowme.net/fullchain.pem:/etc/letsencrypt/live/escrowme.net/fullchain.pem
    - /etc/letsencrypt/live/escrowme.net/privkey.pem:/etc/letsencrypt/live/escrowme.net/privkey.pem

  escrowme:
    build: .
    depends_on:
      - mongodb
    restart: always
  socket:
    build: .
    depends_on:
      - mongodb
    restart: always
  fronetend:
    build:
      context: ../edcrom
      dockerfile: Dockerfile
    restart: always
  admin:
    build:
      context: ../escrame_admin
      dockerfile: Dockerfile
    restart: always
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
